export enum CategoriaProducto {
  LECHE = 'LECHE',
  CARNE = 'CARNE',
  REPRODUCTIVO = 'REPRODUCTIVO',
  SUBPRODUCTO = 'SUBPRODUCTO',
  FORRAJES = 'FORRAJES',
  CONCENTRADOS = 'CONCENTRADOS',
  NUCELOS = 'NUCLESO',
}
